/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -i meegouxsharingdbustypes.h -p ../interfaces/meego-ux-sharing-service_interface.h:../interfaces/meego-ux-sharing-service_interface.cpp ../interfaces/meego-ux-sharing-service.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "../interfaces/meego-ux-sharing-service_interface.h"

/*
 * Implementation of interface class ComMeegoUxSharingServiceInterface
 */

ComMeegoUxSharingServiceInterface::ComMeegoUxSharingServiceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ComMeegoUxSharingServiceInterface::~ComMeegoUxSharingServiceInterface()
{
}

